[build]
  command = "npm run build"
  publish = "build"

[dev]
  command = "npm start"
  targetPort = 3000
  port = 8888
  framework = "create-react-app"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200 